config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :recipes
  resources :recipe_types
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'recipes#index'
end

app/views/layouts/_categories.html.erb
<div class="text-center">
  <h4>Recetas por <strong>Categoría</strong></h4>

  <div class="btn-group">
    <% Category.all.each do |cat| %>
      <%= link_to cat.name, recipes_url(category: cat.id), class: "btn btn-primary"  %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-xl navbar-light bg-warning fixed-bottom">
      Ian<strong>Hein</strong>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

app/views/layouts/_menu.html.erb
<div class="container-fluid">
  <!-- Link a Inicio -->
  <a class="navbar-brand" href="/">Rece<strong>Tario</strong></a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Links de Navegación -->
  <div class="collapse navbar-collapse show" id="navbarDark">
    <ul class="navbar-nav me-auto mb-2 mb-xl-0">
      <li class="nav-item">
        <%= link_to "Recetas", recipes_url, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Categorías", categories_url, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Tipos", recipe_types_url, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Autores", authors_url, class: "nav-link" %>
      </li>
    </ul>
    <!-- Formulario de Búsqueda -->
    <%= form_tag(recipes_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Buscar") %>
    <% end %>
  </div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parcialito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark fixed-top">
      <%= render :partial => "layouts/menu"%>
    </nav>
    <br> <!--La solución a todos tus problemas.-->
    <div class="container" style="margin-top: 100px; padding-bottom: 100px;">
      <%= render :partial => "layouts/categories" %>
    
    </div>
    <%= yield %>
    <%= render :partial => 'layouts/footer' %>
    <!-- Bootstrap 5 JS (Bundled) from CDN -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>
</html>